### ISSUE TITLE
Annotate switch case fall throughs

### ISSUE THREAD

**Issue by TheNicker** [Cyan4973/xxHash#552]
CPP17 allows to annotate switch case fall through using the `[[fallthrough]]` attribute instead of a raw comment.
On newer compilers this cause redundant warnings when compiling with the `-Wimplicit-fallthrough` diagnostic flag.

Example for unannotated switch case fall through at [xxhash.h#L1869](https://github.com/Cyan4973/xxHash/blob/be534ed8c9fa677f18f230735c114373b1ed7d34/xxhash.h#L1869 )

**Comment by TheNicker** [comment]
Resolved in PR #553

**Comment by Cyan4973** [comment]
> On newer compilers this cause redundant warnings.

I've been unable to reproduce this issue.
Could you describe some reproduction procedure ?

**Comment by TheNicker** [comment]
Add `-Wimplicit-fallthrough` to the compilation command. 
I use CLang, but I believe GCC will produce the same results.

**Comment by Cyan4973** [comment]
I could reproduce the issue using `-Wimplicit-fallthrough` flag with `clang-10` and `clang-11` on Ubuntu (though not macos).

Interestingly, the warning issue is still present after merging your PR #553.

```
In file included from xxhash.c:43:
./xxhash.h:1896:12: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
           case 8:       XXH_PROCESS4;
           ^
./xxhash.h:1896:12: note: insert '__attribute__((fallthrough));' to silence this warning                                                                                                                                                                                                                                                                      case 8:       XXH_PROCESS4;
           ^                                                                                                                                                                                                                                                                                                                                                  __attribute__((fallthrough));
./xxhash.h:1896:12: note: insert 'break;' to avoid fall-through                                                                                                                                                                                                                                                                                               case 8:       XXH_PROCESS4;
           ^                                                                                                                                                                                                                                                                                                                                                  break;
./xxhash.h:1898:12: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]                                                                                                                                                                                                                                                          case 4:       XXH_PROCESS4;
           ^
./xxhash.h:1898:12: note: insert '__attribute__((fallthrough));' to silence this warning
           case 4:       XXH_PROCESS4;
           ^
           __attribute__((fallthrough));
./xxhash.h:1898:12: note: insert 'break;' to avoid fall-through
           case 4:       XXH_PROCESS4;
           ^
           break;
./xxhash.h:1903:12: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]

(...)
```

**Comment by TheNicker** [comment]
With Clang 11 and 12 under windows the PR also solves the issue.
Can you send the compilation command ?

**Comment by Cyan4973** [comment]
> Can you send the compilation command ?

`CC=clang-11 CFLAGS=-Wimplicit-fallthrough make xxhsum`

**Comment by TheNicker** [comment]
I've installed Ubunto and Clang and I could recreate the issue.

It appears like `__has_c_attribute` is a C23 feature, that's why `[[fallthrough]]` attribute can't be resolved on some Clang implementations in spite of Clang support of `[[fallthrough]]` in many other implementations. Though it's weird because the LLVM is all about closing these gaps.

In that case, the compiler is right again (what a surprise 😉)

Try compiling #571 and see whether the warnings still persist.

I'm not 100% sure the minimum required Clang version is 3.9. It might be an earlier version which is fine, or a newer one which will require a minor n adjustment in the future.

**Comment by Cyan4973** [comment]
Yep, that fixes the `clang` issue
